[package]
name = "wikipedia-search-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
log4rs = "1.3.0"
memmap2 = "0.9.5"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
